version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 416007387859.dkr.ecr.us-east-1.amazonaws.com/docker

  build:
    commands:
      - echo Building Docker image...
      - docker build -t java .
      - docker build -f ./reactdockerfile -t react .
  post_build:
    commands:
      - echo Tagging Java Docker image...
      - export ECR_URI=416007387859.dkr.ecr.us-east-1.amazonaws.com/ecr
      - docker tag java:latest 416007387859.dkr.ecr.us-east-1.amazonaws.com/ecr:java
      - echo Pushing Java Docker image to Amazon ECR...
      - docker push 416007387859.dkr.ecr.us-east-1.amazonaws.com/ecr:java
      - echo Java Docker image pushed successfully.
      - echo Tagging React Docker image...
      - export ECR_URI=416007387859.dkr.ecr.us-east-1.amazonaws.com/ecr
      - docker tag react:latest 416007387859.dkr.ecr.us-east-1.amazonaws.com/ecr:react
      - echo Pushing React Docker image to Amazon ECR...
      - docker push 416007387859.dkr.ecr.us-east-1.amazonaws.com/ecr:react
      - echo React Docker image pushed successfully.

  artifacts:
    files:
      - '**/*'
    name: your-image-name
    discard-paths: yes
    secondary-artifacts:
      your-artifact-name:
        files:
          - 'image-manifest.json'
        name: your-image-name-manifest
