version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 416007387859.dkr.ecr.eu-west-2.amazonaws.com/docker

  build:
    commands:
      - echo Building Docker image...
      - docker build -t java .
      - docker build -f ./reactdockerfile -t react .
  post_build:
    commands:
      - echo Tagging Java Docker image...
      - export ECR_URI=416007387859.dkr.ecr.eu-west-2.amazonaws.com/hello
      - docker tag java:latest 416007387859.dkr.ecr.eu-west-2.amazonaws.com/hello:java
      - echo Pushing Java Docker image to Amazon ECR...
      - docker push 416007387859.dkr.ecr.eu-west-2.amazonaws.com/hello:java
      - echo Java Docker image pushed successfully.
      - echo Tagging React Docker image...
      - export ECR_URI=416007387859.dkr.ecr.eu-west-2.amazonaws.com/hello
      - docker tag react:latest 416007387859.dkr.ecr.eu-west-2.amazonaws.com/hello:react
      - echo Pushing React Docker image to Amazon ECR...
      - docker push 416007387859.dkr.ecr.eu-west-2.amazonaws.com/hello:react
      - echo React Docker image pushed successfully.
